name: Build LaTeX document
on:
  push:
    paths:
    - '**.tex'
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
        with:
          ref: master
      - name: Compile LaTeX document
        uses: dante-ev/latex-action@master
        with:
          root_file: formule_campi.tex
      - name: Check pdf file
        run: |
          file formule_campi.pdf | grep -q ' PDF '
      - name: Commit files
        run: |
          git config --local user.email "${{ secrets.MY_EMAIL }}"
          git config --local user.name "${{ secrets.MY_NAME }}"
          git commit -m "PDF compilato automaticamente" -a
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
